### ISSUE TITLE
Excel JS API - Attach Debugger Not Working (VSCode)

### ISSUE THREAD

**Issue by thunter05** [OfficeDev/office-js-docs-pr#1820] opened 2020-05-07 17:09 UTC
I'm trying to debug my Excel JS API add-in using VSCode. I am able to debug the UI using the browswer on localhost but I cannot figure out how to debug the Excel context interactions. I cannot find the documentation on how this works. Only see sideloading examples with the UI items in the browser. Nothing on debugging Excel context interactions.

Debugging Link: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdac492e-7568-9c6a-4ac4-1b0e48898141
* Version Independent ID: 8d1c8f9e-1256-8aa5-2b71-284f7b2ec906
* Content: [Excel JavaScript API overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/overview/excel-add-ins-reference-overview)
* Content Source: [docs/reference/overview/excel-add-ins-reference-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/overview/excel-add-ins-reference-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by thunter05** [comment] 2020-05-07 20:07
Thanks mscharlock! I saw these documents as well. So I guess my main question is can I debug my Excel JS API add-in using VSCode? It looks like I can only debug using Visual Studio. I’m pretty bummed about that if so. Thanks again!

**Comment by thunter05** [comment] 2020-05-08 03:45
Hello @mscharlock,

So I found this link below talking about debugging the Excel addin in VSCode. This is saying it’s not supported. I guess I have no idea how someone can test/debug their add-in without having the ability to set breakpoints and see what is going on with the program. I’m nervous that I won’t be able to figure out issues if I can debug the program. Seems like a deal breaker.

https://code.visualstudio.com/docs/other/office

**Comment by mscharlock** [comment] 2020-05-11 17:55
@thunter05 - I am working on documenting a VSCode Extension which will allow for debugging of add-ins with dynamic debugging capabilities. It should roll out very soon, so I will keep you posted!

**Comment by thunter05** [comment] 2020-05-13 19:10
Thanks so much mscharlock! Do you have any sense of when that might happen? I'm kind of flying blind right now when I run into Excel issues.

**Comment by mscharlock** [comment] 2020-05-22 18:58
Hi @thunter05 - Ok, this extension information is up! Docs are here: https://github.com/OfficeDev/vscode-debugger-extension-for-office-addins 
Let me know if you have questions, happy to put you in touch with the engineers on this extension project if you have questions.

**Comment by thunter05** [comment] 2020-05-22 20:40
This is awesome! I’m going. To try it out. Can I use these to trouble shoot custom functions?

**Comment by mscharlock** [comment] 2020-05-22 23:01
It definitely works with Excel and I believe if your custom functions are using the new shared runtime, then this debugger also works with that. (More on shared runtime & adapting your functions to use it here: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime).

**Comment by thunter05** [comment] 2020-05-22 23:13
That is so clutch! I will let try this out tonight and give feedback. I’m currently stuck on trying to fetch from an api using custom functions. I’m trying to post json data and fetch the response. If this helps me figure out the issue I will be thrilled!

**Comment by thunter05** [comment] 2020-05-23 00:32
Hello again @mscharlock,

See screenshot below. I went through the steps listed on the VSCode debugger plug-in. It wouldn't run for me. I changed my "taskpane.html" file to "index.html" when I first created my project. I'm wondering if that is messing with your plug-in? I changed the debugger config to make my html file name but that didn't work. Any thoughts?

<img width="927" alt="office-addin-debugger-failed" src="https://user-images.githubusercontent.com/59625778/82717583-15d5fa80-9c6b-11ea-8f94-663717d15768.png">

**Comment by mscharlock** [comment] 2020-05-27 15:39
Let me tag @TCourtneyOwen - any idea why the above might be happening?

**Comment by TCourtneyOwen** [comment] 2020-05-27 15:54
@thunter05 and I already discussed this [here](https://github.com/OfficeDev/vscode-debugger-extension-for-office-addins/issues/14).  The problem is that they are running Windows 1809, which uses IE as the webview host.  They were unable to upgrade their OS to Windows 1903 so that the add-ins would use the Edge webview host. However, I did provide an alternative for debugging custom functions

**Comment by mscharlock** [comment] 2020-05-27 23:55
Oh super. In that case, I will close this and the other issue can stay open. @thunter05 if you need anything else, feel free to reach out on this thread again and I will reopen it.

**Closed by mscharlock** 2020-05-27 23:55 UTC
Labels: Area: Excel
