### ISSUE TITLE
Tutorial isn't working as expected

### ISSUE THREAD

**Issue by TCourtneyOwen** [OfficeDev/office-js-docs-pr#2332] opened 2020-11-17 23:18 UTC
The tutorial at https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime isn't working as expected.  The taskpane opens but the taskpane is greyed out (see attached image). The custom functions work fine however.

-Courtney

![image](https://user-images.githubusercontent.com/38081557/99462256-200a4600-28e8-11eb-8c47-141ab8267526.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Excel add-in to share the browser runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime)
* Content Source: [docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2020-11-17 23:23
Thanks @TCourtneyOwen, 
Can you please work with @davidchesnut to get this issue resolved?

**Comment by TCourtneyOwen** [comment] 2020-11-17 23:32
@davidchesnut is aware of the issue as well.

-Courtney

**Comment by davidchesnut** [comment] 2021-01-12 22:04
Hi @TCourtneyOwen 

This is something caused by the sideload opening the task pane briefly, then closing it. When the shared runtime opens the task pane, it then won't open properly. You can work around this by:
1. ***File > Close** (to close the workbook with the non-functioning task pane).
2. **File > New > Blank Workbook**.
3. Then use the drop down in the ribbon for **My Add-ins** to find the **Developer Add-ins**. You'll see the sideloaded add-in. Select it and it will work now.

Thanks,
David

**Closed by davidchesnut** 2021-01-12 22:04 UTC
Labels: Area: shared runtime, Needs: attention :wave:

**Comment by TCourtneyOwen** [comment] 2021-01-12 22:29
@davidchesnut interesting, let me give that a shot.  I wonder why the taskpane tries to open

**Comment by TCourtneyOwen** [comment] 2021-01-12 22:32
That's bizarre! It works for me too when following your steps

**Comment by TCourtneyOwen** [comment] 2021-01-12 22:40
@davidchesnut are you updating the tutorial to include this workaround?  Seems like we wouldn't want to have a tutorial the requires a workaround
