### ISSUE TITLE
Still in preview?

### ISSUE THREAD

**Issue by Joel-Intact** [OfficeDev/office-js-docs-pr#1226] opened 2019-08-07 01:23 UTC
Greetings, is this still in preview?  Any word on a release date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e9991e-98d3-bf56-ffbd-c2d77bfb0820
* Version Independent ID: e568baab-36e7-293e-5d6d-6d3b02931004
* Content: [Authorize to Microsoft Graph in your Office Add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph#feedback)
* Content Source: [docs/develop/authorize-to-microsoft-graph.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/authorize-to-microsoft-graph.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by niteshgolchha85** [comment] 2019-08-26 06:35
Closing as this seems to be a duplicate of https://github.com/OfficeDev/office-js-docs-pr/issues/1233

**Closed by niteshgolchha85** 2019-08-26 06:35 UTC
Labels: Needs: attention :wave:, Type: product question
