### ISSUE TITLE
Add-in Error: This add-in is no longer available....

### ISSUE THREAD

**Issue by octocat1000** [OfficeDev/office-js-docs-pr#2297] opened 2020-10-30 18:05 UTC
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial#protect-a-worksheet

## Issue
Completed the tutorial up to the Protect A Worksheet section.  I have followed the instructions to delete caches files (I've deleted all of the files and sub directories from all of the mentioned locations) but am getting an error in Excel which says, "Add-in Error.  This add-in is no longer available.  If this add-in's manifest was removed, please restore it to the previous location and try again."  I've not moved any files, I've only made the changes as per the instructions (as far as I know).

MacOS: 10.14.6
Excel: 16.41

Output of npm start:
> office-addin-taskpane-js@0.0.1 start /Users/<myuser>/Documents/<foo>/Projects/office_add_ins/My Office Add-in
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
The dev server is already running on port 3000.
Sideloading the Office Add-in...
Debugging started.

I'd also like to add that it would be very helpful if the getting started linked off to details for "why" each step is being performed.  There really isn't any explanation about why deleting a cache is necessary in this case, when it would be necessary in any case, so its hard to know (especially as someone trying this for the first time) to know where to look next.

**Comment by AlexJerabek** [comment] 2020-10-30 20:52
Hi @octocat1000, 

Thanks for the feedback. We are looking into this, but I wanted to check in with you about one thing. Your npm start output included "The dev server is already running on port 3000." That leads me to believe the web server is still running, even after the cache clear. Do you encounter the same problem if you give the background process a couple minutes to shutdown (or even restarting your machine) after closing Node.js? That information will help us diagnose the root problem.

Thanks!

**Comment by octocat1000** [comment] 2020-10-30 21:55
Hi @AlexJerabek,

Thanks for getting back.  Just now, I think I've resolved this.  Here is what seems to have been the issue and the things that I tried:

I think that the root culprit was a typo in my manifest wherein I had transposed a couple letters is one of my resid.  After spotting this, deleting all of the cache files and then reloading the app it worked.

I tried turning on debug logging as per the instructions [here](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac) but no log file was generated.  I also run the manifest validation as per the instructions [here](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest) and it passed.  So... not really sure what is a good way to find or debug these kinds of errors...  Any ideas?

**Comment by AlexJerabek** [comment] 2020-11-05 19:53
Let me assign @Rick-Kirkham to investigate the manifest validation issues. @octocat1000, can you please share the issues in your manifest, so we can recreate the problem? Thanks!

**Comment by octocat1000** [comment] 2020-11-05 21:53
Hi @Rick-Kirkham.  I believe that I had just been following the instructions in the tutorial [here](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial#protect-a-worksheet).  I was on the step to add second taskbar items to the manifest and, if I recall correctly, I had transposed the "el" in "ProtectionButtonLabel".

In this section:
`    <Supertip>            
        <Title resid="ProtectionButtonLabel" />
        <Description resid="ProtectionButtonToolTip" />
    </Supertip>
`

**Comment by Rick-Kirkham** [comment] 2020-11-07 02:04
I'm not clear on the issue. Were you expecting that the manifest would not validate given the typo? I don't think that would prevent the manifest from validating. A `resid` is just a string that you choose. The validator will accept any string.

**Comment by octocat1000** [comment] 2020-11-09 18:10
Hi Rick, I have no particular expectations of the manifest validation tool.  However, my question at the start of this thread was how should I be able to find such issues.  In my case, there was no error message anywhere that I could find that led me to understand the cause of the add-in not loading.  So, if the validation tool doesn't catch such errors, how does one come to understand when they occur?  Not sure who is best to answer this.

**Comment by Rick-Kirkham** [comment] 2020-11-12 00:14
I think that I must be missing something.  No system can read a programmer's mind and know what they intended to type.  If a typo causes an error, the system can't tell you that you typed "le" when you meant to type "el". 

Maybe this is why bug forms have sections labelled "Expected" and "Actual". What is your "expected" behavior that you would like to see when you have a typo in a resid?

**Comment by octocat1000** [comment] 2020-11-12 16:52
Rick, it might be good if you read the whole thread.

Ultimately, it came down to a typo in the manifest.  However, the initial error was, "Add-in Error. This add-in is no longer available."  It happened in the same point in the tutorial that talks about having to clear caches by deleting files in multiple locations.  So, at first, I wasn't sure at all why I was seeing this message (i.e. had I delete the wrong files or something).

So, the question now is, how to debug or find logs in order to find this sort of problem.  As I mentioned, I didn't find any logs or anything that pointed me to the cause.  At least, I would hope, there would be a log message somewhere that says there is an error occurring, some clue, something.  As also mentioned, I'm working on a Mac and maybe there is less logging and, it seems, fewer debugging options vs. on Windows?

**Comment by Rick-Kirkham** [comment] 2020-11-12 22:14
This might make me look worse in your eyes, but I actually have reread the whole thread before writing each of my comments. As far as troubleshooting the error in the issue title, I searched for it in Bing and found a number of causes, mostly connected to `resid`s. I think the best I can do is add a section to this article, [Troubleshoot development errors](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors), about this error and describe the causes/solutions to the extent they are known. Does that sound like a good idea? 

BTW, in case  you didn't know this, we do have a system of runtime logging that works on Mac and can catch some issues with manifests. See [Debug your add-in with runtime logging](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging).

**Comment by Rick-Kirkham** [comment] 2020-11-18 20:00
Removing activity status, so the robot won't delete this prematurely.

**Comment by ralphtheninja** [comment] 2021-06-03 09:36
I have the same issue. Trying to start the add-in on Mac but getting the following error:

![image](https://user-images.githubusercontent.com/308049/120623150-c28eae80-c45f-11eb-977d-43956af670cf.png)

I'm running the command `office-addin-debugging start manifests/office-dev.xml desktop`. It used to work but stopped working for no apparent reason.

**Comment by AlexJerabek** [comment] 2021-06-03 18:11
Hi @ralphtheninja,
Thanks for reporting this. Can you please create a new issue on the https://github.com/OfficeDev/Office-Addin-Scripts repo to track this? That'll ensure the right people from yo office are looking into the problem.

**Comment by ralphtheninja** [comment] 2021-08-08 19:08
@AlexJerabek How about re-opening the issue and transferring it to the other repository?

**Comment by ralphtheninja** [comment] 2021-08-08 19:19
Quick re-cap and background

I have the following scripts in my `package.json`:

```
"scripts": {
  "start:excel": "office-addin-debugging start manifests/office-dev.xml desktop --app excel",          
  "start:powerpoint": "office-addin-debugging start manifests/office-dev.xml desktop --app powerpoint",
  "start:word": "office-addin-debugging start manifests/office-dev.xml desktop --app word",            
  "start:outlook": "office-addin-debugging start manifests/outlook-dev.xml desktop"
}
```

Currently Word is working great, `npm run start:word` and boom word shows up with the add-in.

But when I try to start the addin for Excel or PowerPoint I get the error that the add-in is no longer available. If there's some old stuff laying around that should be cleaned up I could simply just try to wipe that information before executing the script as a workaround, if I only knew what needs to be done to get into a good state.

The best way would probably have the `office-addin-debugging` do the clean up needed.

Word works all the time, and I can reproduce the errors in Excel and PowerPoint 100%.

**Comment by ralphtheninja** [comment] 2021-08-08 19:49
Also see https://github.com/OfficeDev/office-js/issues/256

**Comment by ralphtheninja** [comment] 2021-08-08 20:18
Following the troubleshooting section here https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors, I couldn't get any of the paths to fix my problem.

But I found a quick and dirty solution. On Mac I removed the complete `~/Library/Containers/com.microsoft.Excel` folder and it started working again. Doing this is like starting Excel for the first time, since you're greeted with a lets get started dialog.

Similarly, removing `~/Library/Containers/com.microsoft.Powerpoint` solved the problem for PowerPoint. I'm guessing it works for Word as well.

**Comment by AlexJerabek** [comment] 2021-08-09 15:34
Sure thing @ralphtheninja.

@millerds, can you please take a look at this issue, paying particular attention to the information from @ralphtheninja starting on June 3rd? Thank you!

**Comment by montygimpel** [comment] 2021-08-09 22:53
@ralphtheninja deleting files in that folder is not working for me either. While creating Office add-in task pane project using react framework works fine, every time I try create excel custom functions add-in project I get the same error.. add-in no longer available, manifest removed...

I am a mac user. Whats strange is that I can swap in the manifest of the task pane react framework for the manifest created by the custom excel add-in and then excel finds the manifest again. But that manifest then doesnt contain the option to write functions. Similar to original issue in https://github.com/OfficeDev/office-js/issues/256#thread-subscription-status its still fine if only changing certain parts of manifest but then get the error again when changing other parts.

I dont know why excel keep pointing to the manifest created for react framework even though I have deleted the manifest, and all cache. Manifest debugger also says the new manifest has no errors.

**Comment by Sohaibx** [comment] 2021-08-30 19:33
Well................... I'll be damned. I solved this by setting Excel to be Run as Administrator, even when it is being opened by visual studio is debug mode and the error is gone.

**Closed** 2021-09-03 20:56 UTC
Labels: Status: in PR, Area: add-ins
