### ISSUE TITLE
Office.auth.getAccessToken not working with Office on the web (error 13007)

### ISSUE THREAD

**Issue by tlescouezec** [OfficeDev/office-js-docs-pr#3794] opened 2023-01-04 08:04 UTC
## Article URL
https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/troubleshoot-sso-in-office-add-ins.md#13004

## Issue
I'm designing an addIn with custom functions for Excel with SSO. Office.auth.getAccessToken is working both in development and in production mode for desktop Excel. But it generates an error 13007 when using with Office on the web, whatever browser used (Safari, Chrome, Firefox on MacOS - I didn't try on Windows - the user connected is a developer test account provided by Microsoft).
I checked that I had profile and openid permission in app registration on Azure AD and in the manifest file.
As for errors on production mode in the docs, it is unclear. What is a 'Microsoft account identity' (is it the same than MSA which is used without being defined ?) and why this is a problem ?

**Comment by mattgeim** [comment] 2023-01-04 20:50
Hi @tlescouezec,

Thanks for the question - the documentation for 13007 is a bit unclear.  In the case of 'Microsoft account identity' it should indeed be Microsoft account (MSA). We are working to update the documentation to reflect that.

The issue is around account types and application registration.  In the case of the registration, a web application developer can exclude MSA from being able to access the application when it is registered, which will lead to this issue.

Another issue that can occur is related to which Office hosts have been pre-authorized.  [In step 5 of the documentation for registering SSO enabled add-ins,](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2#add-a-scope ) it lists out the various application IDs and what hosts/platforms they go to.  If the all-inclusive one wasn't registered, you would need to confirm that Office on the web was included in your registration. 

You can learn more about application registration and account types in Azure Active Directory at https://learn.microsoft.com/en-us/security/zero-trust/develop/identity-supported-account-types

**Comment by tlescouezec** [comment] 2023-01-05 07:51
Thanks mattgeim for your support.
I checked that:
- supported account types are "Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)"
- Authorized client applications are all platforms ([ea5a67f6-b6f3-4338-b240-c655ddc3cc8e]) which includes Office on the web.
So the problem stays undocumented.
By the way, what the S of MSA stand for, if M is for Microsoft and A for Account ?

**Comment by davidchesnut** [comment] 2023-01-13 21:35
I updated the documentation to better describe the accounts. See #3795 which will go live soon.

**Comment by AlexJerabek** [comment] 2023-02-01 19:56
@davidchesnut, can we close this issue?

**Closed** 2023-03-06 17:39 UTC
Labels: Area: authentication, Type: product question
