### ISSUE TITLE
Binding type for image selection

### ISSUE THREAD

**Issue by rvanlaak** [OfficeDev/office-js-docs-pr#629] opened 2018-12-19 14:15 UTC
## Article URL

https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/bind-to-regions-in-a-document-or-spreadsheet.md

## Issue

What binding type should be used when an image is selected? No binding seem to get added.

Are items like images and graphs missing? https://docs.microsoft.com/nl-nl/javascript/api/office/office.bindingtype?view=office-js

**Comment by AlexJerabek** [comment] 2018-12-20 01:34
Hi @rvanlaak, 

Currently, images are not supported as a BindingType, only what is listed in the [BindingType enum](https://docs.microsoft.com/javascript/api/office/office.bindingtype?view=office-js). You can suggest or upvote feature requests for additional binding types on [UserVoice](https://officespdev.uservoice.com/).

Depending on your scenario, there may be another solution we can help point you towards in the docs. You should also look to [StackOverflow](https://stackoverflow.com/questions/tagged/office-js) for guidance on implementing a solution. Be sure to tag your question with "office-js" so the right people see it.

I'm going to close this issue, since the problem isn't with the documentation itself (this repo is for the documentation and issues associated with it). Please respond to this thread if you need further assistance from us. We can always reopen the issue if needed.

Thanks!

**Closed by AlexJerabek** 2018-12-20 01:34 UTC
