### ISSUE TITLE
Invalid example API referenced in page

### ISSUE THREAD

**Issue by richstr** [OfficeDev/office-js-docs-pr#3395] opened 2022-04-29 13:19 UTC
[The following API is referenced in this page, it is no longer valid - https://www.contoso.com/NumberOfPeopleInSpace]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 667d1e98-4a95-318f-0df1-182722370ac8
* Version Independent ID: f8265387-ba9d-a5db-ef44-8409441b2ece
* Content: [Receive and handle data with custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs)
* Content Source: [docs/excel/custom-functions-web-reqs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-web-reqs.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2022-04-29 15:46
Hi @richstr,

The URL used in that sample was intended to be a hypothetical URL. You replace it with a URL that'll be the data source for your scenario.

I'm going to assign this to @alison-mk to either make that more clear or use a real URL.

**Comment by alison-mk** [comment] 2022-05-03 01:53
Hi @richstr, thanks for submitting this issue. I've updated the article in PR #3403 to address your concern. Once that PR is merged, this issue will close. Let us know if you have any additional questions.

Cheers, 
Alison

**Closed** 2022-05-05 03:29 UTC
Labels: Area: Excel, Type: doc bug, Status: in PR, Area: custom functions

**Comment by richstr** [comment] 2022-05-05 08:26
Thanks!
