### ISSUE TITLE
Documentation Not Working for IE11 Add-In Browser

### ISSUE THREAD

**Issue by thunter05** [OfficeDev/office-js-docs-pr#1915] opened 2020-06-03 19:12 UTC
## Issue
This documentation is not working when the add-in browser is ie11. See my issue post here.
https://github.com/OfficeDev/office-js-docs-pr/issues/1914

**Comment by ElizabethSamuel-MSFT** [comment] 2020-06-05 21:03
Closing as a duplicate of #1914.

**Closed by ElizabethSamuel-MSFT** 2020-06-05 21:03 UTC
Labels: Needs: triage :mag:
