### ISSUE TITLE
Broken link for 5-minute Quick Starts

### ISSUE THREAD

**Issue by mwjo** [OfficeDev/office-js-docs-pr#878] opened 2019-04-08 19:46 UTC
## Article URL
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-ins.md

## Issue
The URL for the "5-minute Quick Starts" in the Next steps section is broken.

URL: https://github.com/OfficeDev/office-js-docs-pr/blob/master/office/dev/add-ins

**Comment by Reezaali** [comment] 2019-04-08 19:59
@mwjo sorry to hear that you had an issue with a broken link. It looks like the "5-minute Quick Starts" link works as expected on [this page](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins) on docs.microsoft.com. I hope this solves the issue. Thanks.

**Comment by mwjo** [comment] 2019-04-08 21:13
Thanks @Reezaali, yes this link works - https://docs.microsoft.com/en-us/office/dev/add-ins/

Could we update the documentation with this link instead?

**Comment by Reezaali** [comment] 2019-04-09 19:43
@mwjo thanks for the suggestion. I did some investigation. Because these docs are intended to be viewed on docs.microsoft.com, this behavior is "by design". I'll go ahead and close the issue now. Thank you.

**Closed by Reezaali** 2019-04-09 19:43 UTC
