### ISSUE TITLE
Unclear documentation on shared runtimes and mulitple taskpanes

### ISSUE THREAD

**Issue by naterush** [OfficeDev/office-js-docs-pr#1954] opened 2020-06-12 18:14 UTC
The documentation for [shared runtimes](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime#multiple-task-panes) notes:
```
Don't design your add-in to use multiple task panes if you are planning to use a shared runtime. A shared runtime only supports the use of one task pane. Note that any task pane without a <TaskpaneID> is considered a different task pane.
```
The wording a bit unclear. Does this mean I can't have multiple show taskpane actions? What if I use the same taskpane id for both of them, like:
```
<Control xsi:type="Button" id="ShareProjectButton">
    ...
    <Action xsi:type="ShowTaskpane">
         <TaskpaneId>MyPane</TaskpaneId>
         <SourceLocation resid="Taskpane.Side.Url"/>
    </Action>
    <Enabled>true</Enabled>
</Control>
<Control xsi:type="Button" id="TaskpaneButton">
    ...
    <Action xsi:type="ShowTaskpane">
         <TaskpaneId>MyPane</TaskpaneId>
         <SourceLocation resid="Taskpane.Main.Url"/>
    </Action>
    <Enabled>true</Enabled>
</Control>
```
When I try the above, it seems like both of these end up as different runtimes, which makes sense as the shared runtime needs to use the same URL throughout the manifest (where as this uses different URLs for each Taskpane).

How would I go about opening different URLs in the taskpane but sharing state between them through the same shared runtime?

Thanks for any information!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Excel add-in to share the browser runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime#multiple-task-panes)
* Content Source: [docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment] 2020-06-12 20:41
@naterush Thanks for asking about this.

@mscharlock Can you take a look?

Thanks.

**Comment by mscharlock** [comment] 2020-06-16 17:25
Let me look into this and get back to you. Thanks!

**Comment by naterush** [comment] 2020-06-16 17:28
@mscharlock awesome, thank you! Very much appreciated :) 

Let me know if any other information or a minimal code sample would be helpful - I can get it to you ASAP if it's a bottle neck.

**Comment by mscharlock** [comment] 2020-06-16 17:58
So, I checked with our PM team and as I suspected, what you are trying to do is not currently possible with shared runtime. If you open different URLs, you'll lose state. However, I've passed your scenario off to our PMs so they are aware of it and you might consider going to UserVoice to request this as a feature if you feel significantly passionate about it. :) Hope that helps answer your question. Let me know if you have additional questions, happy to help.

**Comment by naterush** [comment] 2020-06-17 16:24
@mscharlock Thanks for the info! Good to know - I'll raise this on UserVoice ASAP - so it's possible to develop an add-in just like a standard react web app :)

**Comment by naterush** [comment] 2020-06-17 17:04
Ah -- a quick follow up on a related question.

Per the above discussion, I have a shared runtime and a single ShowTaskpane action. I have other ExecuteFunction operations, that call `Office.addin.showAsTaskpane`, which in the documentation [here](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/show-hide-add-in#show-and-hide-the-task-pane) says will open the Taskpane when called.

However, when `Office.addin.showAsTaskpane` is called from an ExecuteFunction action before the ShowTaskpane button is clicked, this opens the taskpane in new iFrame (rather than the taskpane). Is this expected behavior? It's not in the documentation -- and I'm wondering if there's any way around this behavior.

Thanks for all your help so far - I really appreciate it!

**Comment by lliu113** [comment] 2020-06-29 19:18
@naterush  - thanks for the clarifying question! Launching in a new iFrame is not the expected behaviour, it should display the taskpane. 

Which version of Office are you on? Does clicking the ShowTaskpane button to show the taskpane, closing out and then clicking the ExecuteFunction button get the same result?

**Comment by Murugananths** [comment] 2020-07-02 15:35
@mscharlock ...Hi am also facing some issues while implementing this feature....below are the scenario....

I have Login command (ExecuteFunciton) and logout command(Execute function)

1) Initially when I am clicking Login Command  i was able to enable the commands which are disabled and open the taskpane with respective commands's event id using Office.addin.showAsTaskpane.
2) But if i am trying to click the same Login command or any of other commands (Logout) nothing happened and taskpane page not getting refreshed.
3) When refreshing the browser only taskpane getting refreshed every time on above scenario (Shared Runtime).
4) During normal runtime only taskpane getting refreshed.
Kindly provide your thoughts.

**Comment by mscharlock** [comment] 2020-08-20 18:04
@lliu113, can you have a look at this? Thanks

**Comment by mscharlock** [comment] 2020-08-31 19:31
@Murugananths - do you still need assistance with this? If so, can I ask you to open a separate issue? That will help me funnel this to the right people. Thank you!

**Comment by shaun-pendrigh** [comment] 2022-06-14 11:54
@mscharlock I am facing this issue i.e. using a shared runtime and trying to maintain state while opening different URLs in a task pane. Do you know if this issue was resolved or perhaps I am just doing something wrong still. Thanks

**Comment by AlexJerabek** [comment] 2022-06-15 19:20
It looks like your build supports the [SharedRuntime requirement set](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/common/shared-runtime-requirement-sets?view=common-js-preview).

@davidchesnut, could you please take a look?

**Comment by shaun-pendrigh** [comment] 2022-06-20 12:02
Thanks

@davidchesnut, I have hacked together a small example showing things working with a single task pane and shared runtime. And then a separate branch introducing a second task pane. Here I am not sure how to link the scripts in the html as the example in the documentation only links one of each of the task pane, command and functions scripts. Once there is a second task pane html and script it becomes unclear. The options I have tried so far do not work. Hence my request to at least establish if this is in fact supported before I continue, thanks.

**Comment by shaun-pendrigh** [comment] 2022-07-19 06:11
Just checking for an update on this issue please? I need to make a decision and would really like to confirm what is technically possible before I do, thanks @davidchesnut @AlexJerabek

**Comment by AlexJerabek** [comment] 2022-07-19 17:03
@Rick-Kirkham, could you please help answer @shaun-pendrigh's question?

**Comment by Rick-Kirkham** [comment] 2022-07-19 19:59
@shaun-pendrigh It is not possible to share global state across two distinct task pane URLs. I think you should try to implement your use case some other way. Some possibilities: 

- Have single task pane page, but design it to have tabs. Your add-in instructions would tell the end-user which tab to open in a given scenario. Since it's really one page, both tabs can access the same data. 
- I HAVE NOT TRIED THIS
  Design the page to have two top-level `<div>`s named type1 and type2. Only one is visible by default. Then use the callback function of `showTaskpane` to toggle the visibility of the `<div>`s. 

```
function myFunction() {
    Office.addin.showAsTaskpane()
    .then(function() {
        // Code that sets the visibility status of the <div>s.
    });
}
``` 

- I HAVE NOT TRIED THIS EITHER
  _Maybe_ you can use the `onVisibilityModeChanged` handler to toggle the UI of the page in the task pane. Design the page to have two top-level `<div>`s named type1 and type2. Only one is visible by default. Have the function command code that's going to call `showTaskpane` first set a global variable that specifies which `<div>` should be visible. 

```
let shouldBeVisible = "type2";
function myFunction() {
    Office.addin.showAsTaskpane();
}
```
  Then have the `onVisibilityModeChanged` handler read that variable and toggle the visibility of the `<div>`s as needed.

  ```
  Office.addin.onVisibilityModeChanged(function(args) {
      if (args.visibilityMode = "Taskpane"); {
          if (shouldBeVisible = "type2") {
             // Set type1 <div> to invisible and set type2 to visible.
          }
      }
  });
  ```

  Be sure you are familiar with [Show or hide the task pane](https://docs.microsoft.com/office/dev/add-ins/develop/show-hide-add-in)

- Use [LocalStorage](https://www.w3schools.com/jsref/prop_win_localstorage.asp) to save/retrieve the data that both pages need.  LocalStorage is not deleted when a session ends. To prevent your add-in from using data left over from the last time it was run, either call localStorage.clear() when your add-in starts up or design the add-in so that all your LocalStorage items are rewritten with current values before they are read. 

If you get any of these too work or find some other way to implement your use case, consider creating a sample for our open source samples repo: [Office-Add-in-samples](https://github.com/OfficeDev/Office-Add-in-samples).

I'll close this for now, but you can still make comments and we'll see them.

**Closed by Rick-Kirkham** 2022-07-19 19:59 UTC
Labels: Needs: attention :wave:, Area: add-ins, Area: shared runtime

**Comment by shaun-pendrigh** [comment] 2022-07-21 08:13
Thanks for the confirmation and the options @Rick-Kirkham
