### ISSUE TITLE
Problem with action function in commands.js Excel add-in tutorial

### ISSUE THREAD

**Issue by isaacs-nav** [OfficeDev/office-js-docs-pr#3581] opened 2022-08-09 21:35 UTC
## Article URL

[Protect a worksheet - Excel add-in tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial#protect-a-worksheet)

## Issue
I'm fairly confident I followed the instructions exactly (and even directly pasted the provided code later), but I could not invoke the toggleProtection function in commands.js based off the provided instructions. I spent countless hours debugging and researching the problem. Finally, I overcame the issue by moving the function and accompanying Office.actions.associate() line above the action function in commands.js. The action function is autogenerated when using Yeoman to create the Excel add-in, and the tutorial explicitly states, "Add the following function immediately after the action function."

I noticed the action function uses Office.MailboxEnums, which seems to be specific to the outlook package. So, is the action function supposed to exist for an Excel add-in? If the action function is intended and functional, why would there be an issue with the toggleProtection function existing below the action function?

**Comment by alison-mk** [comment] 2022-08-10 23:45
Hi @isaacs-nav, thank you for submitting this issue! I'll look into your concern and post an update when I have more information.

Cheers,
Alison

**Comment by alison-mk** [comment] 2022-08-18 02:54
Hi @isaacs-nav, I tested the **Protect a worksheet** section of this tutorial and the **Toggle Worksheet Protection** button does work in the add-in I've created, without reordering the methods in commands.js like you suggest. So, I'm not able to reproduce the error that you encountered. I'm sorry to hear that you spent a significant amount of time debugging and researching, though. That sounds frustrating. One commonly missed step is not clearing or fully clearing the Office cache — you must close Excel, run `npm stop` and clear the Office cache any time you want to capture changes to the manifest.xml file. In addition, you'll want to wait a few minutes between running `npm stop` and restarting the server, to ensure that it had time to fully stop. 

I hope this helps. Let us know if you have any additional questions. 

Thanks, 
Alison

**Comment by isaacs-nav** [comment] 2022-08-22 18:38
@alison-mk Thanks for checking into the problem. When I was debugging the issue, I made sure to clear the cache, tested on a different computer, and generated a new Excel add-in multiple times using yeoman. I'm not sure if my node/yeoman versions could've had an impact. No worries if the issues can't be replicated, though.

**Comment by alison-mk** [comment] 2022-08-22 22:15
Ok, thanks for reporting back @isaacs-nav! Since I can't replicate the problem, I will close this GitHub issue. However, even after I close it, this GitHub issue will remain visible in this repository and other users will be able to reference it or add comments to it. If additional customers add comments reporting the same problem, we will reopen the issue and do further testing. 

Thanks again, 
Alison

**Closed by alison-mk** 2022-08-22 22:15 UTC
Labels: Area: Excel, Resolution: cannot repro, Needs: attention :wave:
