### ISSUE TITLE
Change in full code snippet posted

### ISSUE THREAD

**Issue by yernenip** [OfficeDev/office-js-docs-pr#1394] opened 2019-10-26 18:23 UTC
Change this from
 if (!Office.context.requirements.isSetSupported('ExcelApi', '1.1')) {

to

 if (!Office.context.requirements.isSetSupported('ExcelApi', 1.1)) {

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b888399c-fe96-0934-00ce-86db8fa8cf5b
* Version Independent ID: 2c5d24e8-5639-42b1-4d12-119f89591550
* Content: [Convert an Office Add-in project in Visual Studio to TypeScript - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript#feedback)
* Content Source: [docs/develop/convert-javascript-to-typescript.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/convert-javascript-to-typescript.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2019-10-28 18:18
Hi @yernenip, 
Thanks for reporting this. Our current guidance is to use strings for the requirement set version parameter. So, it should be '1.1' through the entire snippet. That step to change it from a string to a number is incorrect. I'll make a PR to address this.

**Comment by AlexJerabek** [comment] 2019-10-28 18:28
The documentation updates have been merged into the master branch. We should see those updates on the live site in the next couple days. 

I'm going to close this issue. Please reply to the thread if there are further concerns.

**Comment by kbrandl** [comment] 2019-10-29 18:03
@AlexJerabek I'm going to re-open this issue, as the Visual Studio (TypeScript) project that's described in this article won't currently compile successfully when the requirement set parameter is set to a string value. i.e., this code:

- ![image](https://user-images.githubusercontent.com/3019529/67795161-14c54d80-fa3b-11e9-85de-05527924dfab.png)

Results in this compile error:

- ![image](https://user-images.githubusercontent.com/3019529/67795214-24dd2d00-fa3b-11e9-8fa1-080f7f3b7787.png)

This problem is caused by the fact that the NuGet package for the Office JS TypeScript Definitions is very outdated:

![image](https://user-images.githubusercontent.com/3019529/67795302-46d6af80-fa3b-11e9-918d-a3aed6922aea.png)

Let's you and I discuss next steps for addressing this sometime soon. Thanks!

**Comment by kbrandl** [comment] 2019-10-29 20:38
PR #1399 addresses the problem that @yernenip reported in this issue. Let's leave this issue open for now, to track the need to update the **office-js.TypeScript.DefinitelyTyped** NuGet package and then:

- update this article to change the requirement set parameter back to a string value (`if (!Office.context.requirements.isSetSupported('ExcelApi', '1.1')) {`)
- update this article to remove the note about the requirement set parameter needing to be a numeric value (and about the NuGet package being outdated)

**Comment by AlexJerabek** [comment] 2019-11-20 19:40
Tagging https://github.com/OfficeDev/office-js/issues/855, as the engineering-side of this issue.

**Comment by AlexJerabek** [comment] 2020-04-10 16:13
Updated the conversion steps to account for the updated office-js NuGet package. You can now use the string version of the requirement set, as per the current recommended guidance. 

Closing this issue.

**Closed by AlexJerabek** 2020-04-10 16:13 UTC
Labels: Area: add-ins, Status: under investigation, Type: doc bug
