### ISSUE TITLE
Latest node lts version not supported

### ISSUE THREAD

**Issue by fhg-isi** [OfficeDev/office-js-docs-pr#4304] opened 2023-12-07 09:50 UTC
The prerequisite "Node.js (the latest LTS version)" should be changed to Node.js (version 18.17.0)

as long as latest LTS version is not supported. 

Also see

https://github.com/OfficeDev/generator-office/issues/793

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator#create-the-add-in-project)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/excel-quickstart-jquery.md)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment] 2023-12-07 22:52
@fhg-isi I need to be clear on the problem before I update the doc. The issue that you linked to mentions:

1. Error about @babel/helper-module-transforms when the Yo Office tool runs `npm install` automatically. I cannot reproduce this on Node.js 20.10.0, npm 10.2.5.
2. **Warning** (not Error) about unsupported Node engine 20.x.x when `npm install` is run manually. I can reproduce this. (Although in my case it happens when Yo Office tool runs `npm install` automatically.) But the installation does complete and the resulting Excel project does work. There is downstream dependency, as Darren mentioned in the issue, that has a limit on compatible Node versions; no higher than 18.x.x. It might be that something in the library really is known to be incompatible with Node 20.x.x or it might be that the maintainers of that library have never tested it with Node. 20.x.x and they have a policy of limiting to tested versions. In either case, however, since the resulting project runs, it seems that any code that's incompatible with 20.x.x (if there really is any) isn't used in the resulting Office add-in. As Darren mentioned a fix is in the works.

So, my inclination is to just add a note to the article telling readers that they can ignore the Warning. 

Can you confirm that the Excel project you created did work in the end?

**Comment by fhg-isi** [comment] 2023-12-08 08:52
Thank you for asking back. 

a) First I tried on a windows system with node version 19. 

b) Then I tried on a ubuntu container. After spening some time with trial and error, it turns out that hosting add ins on linux is not supported (if I understood correctly). => Please include this info in the docs if it is right. Also see
https://github.com/OfficeDev/generator-office/issues/797
and
https://github.com/OfficeDev/generator-office/issues/796

c) 
Today I tried on a different Windows machine where I have enought rights to change the node version. 

I got some warnings during npm install:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm WARN deprecated @azure/msal-node@1.18.4: A newer major version of this library is available. Please upgrade to the latest available version.
npm WARN deprecated @azure/msal-browser@2.38.3: A newer major version of this library is available. Please upgrade to the latest available version.
```

I was able to build and start the "Office Add-in Task Pane project" but it does not seem to work:

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/76424482/4b98fe76-6ec5-441f-be1f-455a576eccee)

**Comment by Rick-Kirkham** [comment] 2023-12-08 19:28
Regarding "b": This is normal. On Linux you can only sideload, test, and run on Office of the Web. See [Debug on Linux](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-overview#debug-on-linux).

Regarding "c": You're getting errors at `npm start`, which I cannot reproduce. The errors indicate that the localhost server is not being started. You can confirm this by putting the URL in from the `<SourceLocation>` element in your manifest into a browser window. If the dev server is running, the page should open (although office.js code won't work). At any rate, this doesn't happen to me, so I think it has no connection to the Node version. I'll go ahead with my plan to add a note about ignoring the warning.

**Closed** 2023-12-11 20:17 UTC
Labels: Area: Excel, Type: doc request, Needs: attention :wave:, Status: in PR
