### ISSUE TITLE
NPM Start not working

### ISSUE THREAD

**Issue by stephenb159** [OfficeDev/office-js-docs-pr#458] opened 2018-10-11 13:54 UTC
when running through this demo, there is an error with npm start. It does not start up, this is true before and after making the configuration changes, so it seems that the yo office generater has problems out of the box. See errors below (I named the project oat)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oat@0.1.0 start: `webpack-dev-server --mode development --https --key ./certs/server.key --cert ./certs/server.crt --cacert ./certs/ca.crt --port 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oat@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6ed3136-1d12-66c2-a8b1-1e7e43553aae
* Version Independent ID: 0e40308a-2d3d-a27b-04d5-1bdd7c09b501
* Content: [Build your first OneNote add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart)
* Content Source: [docs/quickstarts/onenote-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/onenote-quickstart.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment] 2018-10-11 17:16
@stephenb159 thank you for reporting this issue and sorry to hear that you've run into problems with using Yo Office to create a OneNote add-in; we'll investigate.

**Comment by kbrandl** [comment] 2018-10-15 17:40
@stephenb159 I'm unable to reproduce the issue that you've described. I suspect that your problems may be caused by the fact that you're not running the latest version of Yeoman and the Yeoman generator for Office Add-ins.  Can you please run the following command to install the latest versions of these tools globally, and then try creating/testing a new OneNote add-in as described in [Build your first OneNote add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart)? 

    npm install -g yo generator-office

Please let me know the result once you've had a chance to do this. Thanks!

**Comment by kbrandl** [comment] 2018-10-17 17:00
@stephenb159 per my previous comment in this thread, I'm going to go ahead and close this issue now. Please feel free to re-open it if installing the latest versions of Yeoman and the Yeoman generator for Office Add-ins doesn't solve your problem. Also, please note that this article was updated yesterday to address some other minor issues.

**Closed by kbrandl** 2018-10-17 17:00 UTC
Labels: area: add-ins
