### ISSUE TITLE
Using Word APIs in Powerpoint add-in

### ISSUE THREAD

**Issue by safwatalikhan** [OfficeDev/office-js-docs-pr#1636] opened 2020-02-29 18:58 UTC
Is there any way to use Word APIs for a Powerpoint add-in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445e0856-5979-1c2d-8bab-c6294675be79
* Version Independent ID: aa56948e-b70e-43af-8a62-4c6cbfd14335
* Content: [Office JavaScript API support for content and task pane add-ins in Office 2013 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/support-for-task-pane-and-content-add-ins#feedback)
* Content Source: [docs/develop/support-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/support-for-task-pane-and-content-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2020-03-02 18:18
(Duplicate of https://github.com/OfficeDev/office-js-docs-reference/issues/644 - reposting the answer given there.)

Hi @safwatalikhan, 

Thank you for your question. The Word APIs are specific to Word and cannot be used in any other host. You can read about the differences between the Host-specific APIs and the Common APIs [here](https://docs.microsoft.com/office/dev/add-ins/develop/understanding-the-javascript-api-for-office?view=excel-js-preview#api-models).

I'd recommend going to UserVoice and voting for [this PowerPoint API suggestion](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/33200554-powerpoint-api). Community input helps us prioritize new feature work.

I'm going to close this issue, as there's no actionable item we can take in the reference documentation.

**Closed by AlexJerabek** 2020-03-02 18:18 UTC
Labels: Area: PowerPoint, Resolution: not actionable, Type: product question
