### ISSUE TITLE
Can't debug Outlook adding for latest office version

### ISSUE THREAD

**Issue by ivgenibr** [OfficeDev/office-js-docs-pr#1603] opened 2020-02-19 09:43 UTC
For office versions &gt;= 16.0.11629 (according to this doc: https://docs.microsoft.com/nl-nl/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins), one should use the Microsoft Edge debugging approach.
However the "Microsoft Edge DevTools" application does not show any targets related to Outlook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6ad3bb-b3fe-e8c6-4a38-f6df85dbabf4
* Version Independent ID: 194afc55-e012-edc5-da88-9858f1d52f34
* Content: [Debug add-ins using developer tools on Windows 10 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10#feedback)
* Content Source: [docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2020-02-20 20:34
Closing as a duplicate of #1613. Please comment on the thread if that is not the case and I'll reopen it.

**Closed by AlexJerabek** 2020-02-20 20:34 UTC
Labels: Area: Outlook, Resolution: duplicate
