### ISSUE TITLE
No complete example for the complete Mobile supported Manifest.

### ISSUE THREAD

**Issue by AjitHogade** [OfficeDev/office-js-docs-pr#687] opened 2019-01-16 06:34 UTC
Atleast can provide a complete Example so that it would be more clear about the "VersionOverrides schema", because getting the above lines of code and updating in existing manifest with changed version of "VersionOverrides schema" wont help here, also after following the these documents I have investigate a lot on other sources to fins out the actual solutions. Documentation must be complete and easy to understand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: affdd12b-810b-8223-25ad-0f06ebf065f9
* Version Independent ID: 5f05e9b5-b68e-8cc0-5fbb-75e81ff4568d
* Content: [MobileFormFactor element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/mobileformfactor#mobileformfactor-example)
* Content Source: [docs/reference/manifest/mobileformfactor.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/mobileformfactor.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment] 2019-01-18 22:03
Hi @AjitHogade - thanks for writing in and reading the Office add-ins documentation. Sorry to hear you are having an issue with the manifest documentation. A complete example of a manifest file [can be found here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1#manifest-v11-xml-file-examples-and-schemas), which hopefully should help! Let me know if that's helpful or if you need additional guidance. Happy to help!

**Comment by danjyoung** [comment] 2019-01-30 05:45
@mscharlock - I believe @AjitHogade was asking specifically for a complete example of a MobileFormFactor manifest snippet. Is the mobile the same as desktop just different namespace to provide different values for the same declarations?

**Comment by mscharlock** [comment] 2019-02-06 22:32
@danjyoung thanks for the input on this - definitely helped me get some clarity about the original question. 

@AjitHogade it’s by design that XML examples in manifest element reference articles like [MobileFormFactor element]( https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/mobileformfactor) contain only the XML markup to demonstrate the structure of that particular element (and not the full XML manifest file). There are some complete XML manifest file examples in the [Office Add-ins XML manifest]( https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1#manifest-v11-xml-file-examples-and-schemas ) article as I mentioned– but those examples don’t show every possible combination of elements an XML manifest file may contain.  

However, you're in luck: you can find an example of a manifest that uses the `<MobileFormFactor>` element in the [OfficeDev/outlook-add-in-command-demo]( https://github.com/OfficeDev/outlook-add-in-command-demo) sample repository (specifically, in the [command-demo-manifest.xml]( https://github.com/OfficeDev/outlook-add-in-command-demo/blob/master/command-demo-manifest.xml) file). 

Let me know in a comment here if that doesn't provide the info you need - I'm happy to help.

**Comment by kbrandl** [comment] 2019-02-07 16:35
@AjitHogade I'm going to close this issue, since @mscharlock has provided guidance for you. Please feel free to comment again here if you need further info. Thanks!

**Closed by kbrandl** 2019-02-07 16:35 UTC
Labels: area: add-ins
