### ISSUE TITLE
Visual Studio approach add in does not load

### ISSUE THREAD

**Issue by brad302** [OfficeDev/office-js-docs-pr#2598] opened 2021-04-04 12:42 UTC
I followed the steps and created a project in VS 2019 which resulted in an Excel add in that simply wouldn’t load. It errors telling me it failed to install.

I tried the project as vanilla and didn’t follow the steps to change the contents of the JS files and still no love.

I’d try and provide more details but it’s a black box and I get no output telling me why it fails.

Very keen to get some guidance on where to look and how to correct it.

Thanks

Brad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2021-04-05 16:15
Hi @brad302, 

Sorry to hear you're unable to get the quick start working. I have a few questions to help us debug the situation:

1) What version of Excel do you have? You can find this under **File** > **Account** (please give us the version and build number).
2) Is an Excel workbook launching when you run the Visual Studio project? Does the workbook open, but the add-in taskpane not display anything (other than an error)?
3) Have you tried clearing the Office cache? Sometimes, Office gets in a weird state during add-in development and you have partial add-ins blocking each other. You can find the cache clearing steps here: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache
4) Is the [Yeoman Generator version](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator) of the quick start working for you? That can help us diagnose where the problem is.

Thanks Brad!

**Comment by brad302** [comment] 2021-04-06 02:47
@AlexJerabek, all good, I'm sure it's something I'm doing and I'm sure we'll work it out.

To answer your questions ...

1. Excel version 2103 (Build 13901.20230 Click-to-run)
2. Yes, it launches Excel, shows the button in the ribbon to display the taskpane but fails after that.
3. Yes and just tried again but no luck.  When in the Edge DevTools, it doesn't give me anything as such.  The local project appears but all that comes up is "about:blank".  Something is clearly unhappy.
4. Yes, the Yeoman generator does work, of course I could use that but prefer VS for development and was keen on the quick start from VS to get going.

Have attached some screenshots for you, hopefully that helps.  I'm also happy to have a Teams session if that suits.

Brad

[Excel JS Addin Issue Steps Taken.docx](https://github.com/OfficeDev/office-js-docs-pr/files/6261690/Excel.JS.Addin.Issue.Steps.Taken.docx)

**Comment by AlexJerabek** [comment] 2021-04-06 15:12
Thanks for all that information @brad302.

It's possible the VS workload is out of date. Let me assign this to @mattgeim to investigate.

**Comment by brad302** [comment] 2021-04-07 03:16
Thanks @AlexJerabek.  @mattgeim, I'm here when you're ready.  Hopefully sooner rather than later.  Pretty keen to solve this one.

**Comment by brad302** [comment] 2021-04-16 09:49
@mattgeim, sorry mate but any update by chance?

**Comment by AlexJerabek** [comment] 2021-04-16 17:27
I'll also tag @TCourtneyOwen and @akrantz to help investigate. Could either of you please take a look at this issue today?

**Comment by TCourtneyOwen** [comment] 2021-04-16 17:30
Adding @millerds @igor-ribeiiro

**Comment by igor-ribeiiro** [comment] 2021-04-19 18:48
@brad302 I just tried the Visual Studio tutorial following the tutorial: [https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visualstudio](url) and it worked. I tested both changing the files as requested and just running the project as it it. Both of those worked here.

I think that the problem might be that you didn't accept the certificate that appears when you run the add-in. Did you accept it?

**Comment by brad302** [comment] 2021-04-19 22:02
@igor-ribeiiro that may very well be the case but it's not prompting me to accept anything. The doco says "IF" you are asked, but I am not. I actually don't recall it ever asking me. Are there any manual workarounds or alternative procedures you know of?

**Comment by igor-ribeiiro** [comment] 2021-04-20 18:17
@brad302 maybe you set-up it in the past to not accept the certificate and ask for the prompt to not ask again, but I guess this is not the problem, as you would be getting a security warning if that was the case

A search on the error that appears for you "this add-in could not be started" made me find the following link that you can also test: [https://support.cloudextend.io/en/articles/1689593-add-in-error-this-add-in-could-not-be-started-close-this-dialog-to-ignore-the-problem-or-click-restart-to-try-again](url)
I tested it on my pc and it still load the add-in after that, but it was already loading it beforehand, so I'm not 100% sure this will fix your problem, but it is worth the try.

**Comment by brad302** [comment] 2021-04-21 10:13
@igor-ribeiiro will check that out, in the meantime, can you attach a compressed zip file of the project that works for so I can see how it behaves on my machine?

**Comment by igor-ribeiiro** [comment] 2021-04-21 16:27
@brad302 The compressed file is too big to be sent here (max 10MB and the file is 60MB). So it is not easy for me to send it.
But as I said, I just created the project normally, you should have the same project as me.

**Comment by brad302** [comment] 2021-04-21 23:08
@igor-ribeiiro that may be the case but for me to run your project eliminates VS from the equation, standard troubleshooting approach.  It then squarely puts it back to something to do with my environment.  Either way, that suggestion in the link didn't work for me.

**Comment by igor-ribeiiro** [comment] 2021-04-22 16:51
@brad302 sure, thanks for trying the suggestion I sent. Could you try running with `runtime logging`?
This would provide better error messages and would help us both debug this: [runtime logging](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging)

**Comment by brad302** [comment] 2021-05-26 11:54
@igor-ribeiiro, apologies for not having done what you requested, I've been incapacitated but will try in the coming days.

**Closed** 2022-03-05 04:00 UTC
Labels: Status: no recent activity, Area: Excel, Type: product bug, Needs: author feedback
