### ISSUE TITLE
Shared Runtime Requirement sets and Word (/ multi-host manifest)

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js-docs-pr#3792] opened 2023-01-03 10:54 UTC
Hi, is it still the case that adding the Shared Runtime Requirement will break Word Addins?  do we have an eta on a fix for this?

We currently have one manifest for 3 hosts (Excel, Powerpoint and Word), is it possible to specify the requirement set per host?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Office Add-in to use a shared runtime - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime?view=excel-js-preview)
* Content Source: [docs/develop/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2023-01-04 19:35
Thanks for the question @theboyknowsclass.

 @davidchesnut, do you have any insight?

**Comment by AlexJerabek** [comment] 2023-02-01 19:59
Tagging @penglongzhaochina to see if they have an answer.

**Comment by penglongzhaochina** [comment] 2023-02-06 07:32
Hi @madhavagrawal17 Could you please take a look?

**Comment by davidchesnut** [comment] 2023-02-06 16:48
Sorry, I didn't see this sooner. @theboyknowsclass, the shared runtime 1.1 works for Excel, Word, and PowerPoint. See [Shared runtime requirement sets](https://learn.microsoft.com/javascript/api/requirement-sets/common/shared-runtime-requirement-sets) for full support details. If you need the functionality in 1.2, then that only runs on Excel.

Can you share more details about the error (if any you are seeing) or the behavior that's causing the issue? If you can share a manifest that reproduces the behavior that would help as well. Thanks!

**Comment by theboyknowsclass** [comment] 2023-02-06 16:53
![image](https://user-images.githubusercontent.com/2139941/217033848-8f40ee69-b4c3-4820-a949-200314072541.png)

i don't see any error, in fact I was confused that I didn't because of the above note on the docs

**Comment by theboyknowsclass** [comment] 2023-02-06 16:59
i.e.

https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/configure-your-add-in-to-use-a-shared-runtime.md?plain=1#L53

**Comment by davidchesnut** [comment] 2023-02-10 23:38
Ah, yes it looks like that issue is fixed and no longer applies. Let me confirm with the team and I'll make an update to the docs. Thanks!

**Comment by davidchesnut** [comment] 2023-02-23 23:34
Fixed in #3868

**Closed** 2023-03-04 00:47 UTC
Labels: Status: fixed, Type: product question, Area: shared runtime
