### ISSUE TITLE
Outlook add-in side-load link 404

### ISSUE THREAD

**Issue by ToddBoothroyd** [OfficeDev/office-js-docs-pr#1518] opened 2019-12-30 16:50 UTC
The link to side-loading an Outlook add-in is resulting in a 404 error.

**Comment by kbrandl** [comment] 2019-12-30 17:28
@ToddBoothroyd thanks for reporting this issue. Can you please add a comment here to indicate the page (URL) where this broken link exists? Thank you!

**Comment by ToddBoothroyd** [comment] 2019-12-30 21:34
The link exists on this page:
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md
"Sideload Outlook add-ins for testing"
404: https://github.com/OfficeDev/office-js-docs-pr/blob/master/outlook/add-ins/sideload-outlook-add-ins-for-testing

**Comment by kbrandl** [comment] 2019-12-30 21:47
@ToddBoothroyd thanks for the additional info! 

Apologies for the confusion that this may have caused, but this behavior is actually expected / by design. i.e., the GitHub files here in the **OfficeDev/office-js-docs-pr** repository represent the source files that are used to produce the actual doc set here:  https://docs.microsoft.com/en-us/office/dev/add-ins. Any links in the GitHub source files that point to a file in another GitHub repo (like the one you've noticed, which points to a file in the **OfficeDev/outlook-dev-docs** repo) will return a 404 (since all links are relative -- the link attempts to resolve to a file in the *same* repo, but that file doesn't exist there).

I'd recommend that you explore the Office Add-ins documentation from the docs site itself (https://docs.microsoft.com/en-us/office/dev/add-ins), rather than via the docs source files here in GitHub. For example, if you navigate to that page in the doc set (https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins) and click the **Sideload Outlook add-ins for testing** link there (https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing), you should be successfully navigated to the **Sideload Outlook add-ins for testing** article. 

Hopefully this guidance is helpful. I'm going to go ahead and close this issue now, but if you have anything else to add, please feel free to continue the conversation with me here. Thanks!

**Closed by kbrandl** 2019-12-30 21:47 UTC
Labels: Area: add-ins, Type: doc bug
