### ISSUE TITLE
Buttons Dont Work?

### ISSUE THREAD

**Issue by RyanSpagnuolo** [OfficeDev/office-js-docs-pr#3921] opened 2023-03-17 13:42 UTC
I am having issues with the PowerPoint Create a PowerPoint task pane add-in tutorial and getting the code to run. Any help would be much appreciated! 
https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/powerpoint-tutorial

**Comment by ElizabethSamuel-MSFT** [comment] 2023-03-17 14:27
@alison-mk Can you take a look?

@spags09 Sorry to hear that you're hitting issues.

Can you provide as many details as you can to help us repro and debug?

## Your Environment
#### Include as many relevant details about the environment so we can triage your issue
* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior
#### Tell us what you expected to happen
___

## Current behavior
#### Tell us what happens instead of the expected behavior
___

## Steps to reproduce
#### If we cannot reproduce the issue, we cannot triage
1. ______
2. ______
3. ______

## Useful logs
#### Please include any of the following logs that may help us debugging your issue
- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thanks.

**Comment by spags09** [comment] 2023-03-17 14:46
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: PowerPoint
Office version number: Microsoft® PowerPoint® for Microsoft 365 MSO (Version 2208 Build 16.0.15601.20540) 64-bit 
Operating System: WIN10
Browser (if using Office on the web): Edge Dev

I am expecting to click the Image Button and have it populate Bing Image of the day onto the ppt slide. But when I click the button nothing happens. When I add the other buttons, as outlined in the tutorial, nothing happens with each of them when clicked. Im sure it is user error at this point since I am new to this and trying to teach myself with this tutorial. I just dont understand why its not working at this point - not sure how to troubleshoot. 

Thanks for the quick response and help!! :)

**Comment by alison-mk** [comment] 2023-03-17 19:53
Hi @spags09, thanks for submitting an issue. Which version of Visual Studio are you using to build the project? Please check whether it's Visual Studio 2019 or 2022, and then provide the version number within. This will help us test properly. 

In my preliminary testing in Visual Studio 2019, I noticed that the Home.html file is referencing a version of jQuery that isn't present in the project files. Line 7 in Home.html should read: 

`<script src="Scripts/jquery-3.6.4.js" type="text/javascript"></script>`

I'm working on a solution for this discrepancy. Let me know if this jQuery fix resolves your issue. 

If your add-in still isn't working, try exploring our debugging docs for Visual Studio: [Debug an Excel, PowerPoint, or Word add-in project](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/debug-office-add-ins-in-visual-studio#debug-an-excel-powerpoint-or-word-add-in-project) to see if the add-in is returning console errors. In particular, start the add-in and then use the personality menu to attach a debugger: 

<img width="309" alt="image" src="https://user-images.githubusercontent.com/7977793/226015496-19091e20-df40-4757-8ece-37c970e3d9fe.png">

If you're seeing console errors, please report back with those. 

Thanks, 
Alison

**Comment by spags09** [comment] 2023-03-17 20:26
Alison -
Thanks for the quick response! That definitely made the difference. I am now just receiving a console error when clicking "Insert Image". Below is the concole error. How do I provide access?
[cid:67aa8914-4a74-4c67-b7a5-6f312fb1dda9]
- Ryan
________________________________

**Comment by alison-mk** [comment] 2023-03-17 22:20
@spags09 It looks like the image you tried to include didn't make it through the system. Could you type out the error, or paste the image into the GitHub issue? 

Thanks, 
Alison

**Comment by spags09** [comment] 2023-03-20 16:41
@alison-mk here is the text file from the console. 

[Bing Image Console Error.log](https://github.com/OfficeDev/office-js-docs-pr/files/11020786/Bing.Image.Console.Error.log)

**Comment by alison-mk** [comment] 2023-03-31 18:29
Hi @spags09, I can replicate this bug with the image — selecting Insert Image in **Test the add-in** step 3 returns a 404 error in the console — but unfortunately I don't have a solution for it yet. I'm researching the issue internally. 

Regarding the jQuery version, I'm updating my guidance. The jQuery version installed with the Visual Studio solution matches the jQuery call within the solution files, and it should not be updated. I suspect that when you used the NuGet Package Manager to install the required packages, you also ran the suggested updates (which is what I did initially, too) and that's why jQuery initially threw an error. I've added a note to the tutorial to clarify this point. 

I'll leave this issue open while we work to resolve the 404 error. 

Thank you, 
Alison

**Comment by ElizabethSamuel-MSFT** [comment] 2023-09-15 16:14
@RyanSpagnuolo We're working on a fix for this. Please do try out the updated instructions in [the related PR](https://github.com/OfficeDev/office-js-docs-pr/issues/3921) and let us know if you're still facing issues.

Thanks.

**Closed** 2023-09-15 19:45 UTC
Labels: Area: PowerPoint, Type: doc bug, Status: in PR
