### ISSUE TITLE
Outlook Plugin Visual Studio Code debugger not working 

### ISSUE THREAD

**Issue by sid1260** [OfficeDev/office-js-docs-pr#3150] opened 2021-12-22 21:06 UTC
This does not seem to be working as mentioned in the article. If we try to do as suggested below is the exception received
![image](https://user-images.githubusercontent.com/38790296/147155121-780f04fe-c73a-4fb8-ac24-ff74898b8b69.png)
This is the debugging config in launch.json
{
      "name": "Outlook Desktop (Edge Legacy)",
      "type": "office-addin",
      "request": "attach",
      "url": "https://localhost:3000/taskpane.html?_host_Info=Outlook$Win32$16.01$en-US$$$$0",
      "port": 9222,
      "timeout": 600000,
      "webRoot": "${workspaceRoot}",
      "preLaunchTask": "Debug: Outlook Desktop",
      "postDebugTask": "Stop Debug"
    },

I have also tried to use 
{
      "name": "Outlook Desktop (Edge Chromium)",
      "type": "edge",
      "request": "attach",
      "useWebView": "advanced",
      "port": 9229,
      "timeout": 600000,
      "webRoot": "${workspaceRoot}",
      "preLaunchTask": "Debug: Outlook Desktop",
      "postDebugTask": "Stop Debug"
    },
This throws exception saying edge is no more supported. 

In the end both options seems to fail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614e6992-f9be-4ce5-1f15-0fc6bf285c43
* Version Independent ID: 1b37e38d-06ec-cd00-16bb-3324b1f0048f
* Content: [Microsoft Office Add-in Debugger Extension for Visual Studio Code - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension?source=docs)
* Content Source: [docs/testing/debug-with-vs-extension.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-with-vs-extension.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2021-12-22 22:30
Hi @sid1260,

Thank you for reporting this. I just reproduced your issue. I'll tag @darrenmart to help find a solution.

**Comment by AlexJerabek** [comment] 2021-12-22 22:31
Also tagging @igor-ribeiiro to help investigate.

**Comment by AlexJerabek** [comment] 2021-12-22 22:46
@sid1260, One quick question, do you have the same experience if you select "Outlook Desktop (Edge Chromium)" from the "Run and Debug" menu?

![image](https://user-images.githubusercontent.com/38896772/147163429-261d7be3-b657-4f9d-8174-9cf883e99c86.png)

**Comment by sid1260** [comment] 2021-12-23 08:23
If I choose edge chromium , I get a warning 
![image](https://user-images.githubusercontent.com/38790296/147210879-80d33403-17c8-40ed-9951-d39e65bb63b8.png)

Then once outlook opens and after opening the task pane, below error pops up

![image](https://user-images.githubusercontent.com/38790296/147210963-1c2c0f3a-ecb6-40cb-b7e6-035aef8c3b0d.png)


Let me know if you need more info. Are you able to reproduce this behaviour?

**Comment by millerds** [comment] 2022-01-03 23:37
I'm a little confused here.  The step linked to here are for running dev server first and attaching to it using the launch config code in the instructions added to the config file . . . but the discussion here is talking about using the existing launch configs in our templates which don't require running dev server first.  What are the specific steps of the repro?

**Comment by sid1260** [comment] 2022-01-04 09:01
Hi Millerds, if you start the dev server and try to attach you end up with the same issue. Either ways for Outlook, it looks like debugging does not work.

**Comment by millerds** [comment] 2022-01-04 18:51
If I create a new project for an outlook task pane using 'yo office' and use the chromium debugger command provided it doesn't have either of those errors.

I have seen that first error when trying to use the wrong debugger (Legacy when the browser being used is Chromium), but the other one I have not seen.  Can you tell me more about your environment (version of Office, VS Code, Edge, OS, Node, and npm)?

**Comment by sid1260** [comment] 2022-01-07 08:28
version of Office - Version 2111 Build 14701.20262
VS Code Version 1.6
Edge - Microsoft Edge Version 96.0.1054.62
OS  Windows 10 Enterprise
Node - v.14.18.1
npm - 8.0.0

**Comment by sid1260** [comment] 2022-01-07 08:58
Here's a video grab. Let me know if something strikes 
https://drive.google.com/file/d/1MEi95QSqvaK6A-DOfBiS1GLsU4q8fjSI/view?usp=sharing

**Comment by millerds** [comment] 2022-01-07 20:33
OK, I can get that error when I disable my "Debugger for Microsoft Edge" extension (I noticed some extension error in your video). Looks like the debugging plugins have changed and our templates need to be updated.  In the meantime, if you change your launch.json entries from "type": "edge" to "type": "pwa-msedge" then your chromium entries should work.

**Comment by sid1260** [comment] 2022-01-07 23:38
It better..but..

If I change to pwa-msedge, the error goes away, however the breakpoint never gets hit.
See here https://drive.google.com/file/d/183VOFt9oUPyfT9NLBe5Jd1ImdYKcQ7R5/view?usp=sharing

Are you able to hit the breakpoint?

**Comment by millerds** [comment] 2022-01-07 23:54
OK . . . looks like the useWebView config setting has changed type.  Change 

    "useWebView": "advanced" 

in the launch.json file to be 

    "useWebView": true

**Comment by sid1260** [comment] 2022-01-08 08:49
I did that. Still the same, unable to debug,its not hitting the debug points.

![image](https://user-images.githubusercontent.com/38790296/148638134-61f66be4-84dc-4f4a-952f-015db7b2296a.png)

**Comment by millerds** [comment] 2022-01-10 17:50
No quotes around the 'true' . . . it needs to be a boolean value not a string.

**Comment by sid1260** [comment] 2022-01-10 20:18
ahh. Good catch.
 
![image](https://user-images.githubusercontent.com/38790296/148833243-a9f1c2d3-c973-4018-8063-c910f0532600.png)

Unfortunately no luck :(

**Comment by millerds** [comment] 2022-01-10 23:30
So after making those two modifications I'm able to hit breakpoint in a new project for Outlook.  Can you explain what your current experience is including specific steps on what you are trying to do?

**Comment by sid1260** [comment] 2022-01-11 07:59
I have added breakpoints to taskpane.js , then started the debug process, but it does not hit the breakpoint. 
Added a video recording.

https://drive.google.com/file/d/1_KxFIbMU7QJMJd9fF7tB62l-sIbrky_W/view?usp=sharing

**Comment by millerds** [comment] 2022-01-11 19:20
OK . . . let's look at some more environment information.  Can you let me know:

- The type of Office install (32 vs. 64 bit and if it O365/"click-to-run" or a standalone install (like Office 2019)
- The plugins you have installed for VS Code
- The output of running "npx office-addin-dev-settings webview manifest.xml" in your project

**Comment by sid1260** [comment] 2022-01-11 20:47
The type of Office install (32 vs. 64 bit and if it O365/"click-to-run" or a standalone install (like Office 2019)
> Its 64 bit o365 click to run

The plugins you have installed for VS Code
>Here are the list of VS code plugins
 code --list-extensions | % { "code --install-extension $_" }
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension flowtype.flow-for-vscode
code --install-extension hashicorp.terraform
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.powershell
code --install-extension mshdinsight.azure-hdinsight
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.vscode-react-native
code --install-extension msoffice.microsoft-office-add-in-debugger
code --install-extension redhat.vscode-yaml
code --install-extension scala-lang.scala
code --install-extension tht13.python
code --install-extension vscode-icons-team.vscode-icons

The output of running "npx office-addin-dev-settings webview manifest.xml" in your project
>PS C:\Temp\officeoutlookplugin\testproject> npx office-addin-dev-settings webview manifest.xml
The web view type has not been set.

**Comment by millerds** [comment] 2022-01-11 22:04
Can you check if WebView2 is install on your machine (using 'Add or remove programs' settings)?

Also run 'npx office-addin-dev-settings webview manifest.xml edge' and try debugging again.

**Comment by sid1260** [comment] 2022-01-11 22:19
Yes, webview2 seems to be there
![image](https://user-images.githubusercontent.com/38790296/149029943-05937202-a2ac-4652-8f5d-e3d3ab3e3e49.png)

Did the change
![image](https://user-images.githubusercontent.com/38790296/149030242-7f9f0baf-de32-4124-ad70-0c66c1d77b37.png)

Still no luck

**Comment by sid1260** [comment] 2022-01-26 15:42
hi Millerds, 
Any update on the above?

**Comment by millerds** [comment] 2022-01-28 21:50
Are you able to provide a zip file of the project (remove the nod_modules folder first)?

**Comment by millerds** [comment] 2022-02-14 19:02
I am able to debug your project just fine . . . so it's definitely something about the environment.  I can't see anything wrong with the environment information you've given me, but may just try getting an update version of VS code and Office (if possible).

**Comment by sid1260** [comment] 2022-02-15 21:06
version of Office - Version 2102 Build 13801.21092
VS Code Version 1.63.2

**upgraded to** 
VS Code Version 1.64.2
Office version (16.0.14326.20782) 64-bit

And voila - we have a winner :)

![image](https://user-images.githubusercontent.com/38790296/154148979-b48bf6b9-b186-4bc8-a91a-015abad978bc.png)

Not sure what and how. But glad that is working. Thanks for the patience and help!!

**Comment by millerds** [comment] 2022-02-15 22:08
Glad it worked!

**Comment by AlexJerabek** [comment] 2022-02-15 22:11
Thanks @millerds!

Since the updating to the latest versions of VS Code and Office solved the problem, I'm going to close the issue. If I'm mistaking and there's a documentation issue that needs to be addressed, please let me know and I'll reopen it.

**Closed by AlexJerabek** 2022-02-15 22:11 UTC
Labels: Type: product bug, Needs: attention :wave:, Area: add-ins
