### ISSUE TITLE
Dialog is closed automatically after a 5 minute timeout using displayDialogAsync in Outlook Mail Web app

### ISSUE THREAD

**Issue by digiofficerobin** [OfficeDev/office-js-docs-pr#4840] opened 2024-10-08 14:41 UTC
**Article URL**
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

**Describe the problem**
We have an app which shows a form in a dialog using the displayDialogAsync method. The dialog and the content are shown correctly. But after approx 5 minutes the dialog is closed automatically and the following message is shown to the user:

`We're sorry, we couldn't access <Appname>. Make sure you have a network connection. If the problem continues, please try again later.`

Is there an undocumented feature which require an app to tell Outlook it is still alive?
If so, how can we implement this?

The issue can be replicated with the following steps:

1. Install the public available 'Script Lab for Outlook' from the app store
2. Launch https://outlook.office365.com/mail/
3. Create empty e-mail
4. Click on Apps icon
5. Click on app 'Script Lab for Outlook'.

![image](https://github.com/user-attachments/assets/e7c06f50-7954-4814-b479-2a30fd310202)

6. Click on 'Ask the Community' or 'Reference Docs'
![image](https://github.com/user-attachments/assets/c00cdeb7-64bc-40cc-bdfc-4a602a1432ca)

7. A modal dialog is shown. Let this dialog shown for at least 5 minutes.

![image](https://github.com/user-attachments/assets/193307d3-6b48-4fb7-aedc-c4410d196763)

After this time the dialog is closed automatically and the following error is shown in Outlook.
![image](https://github.com/user-attachments/assets/ad2c895c-0fef-439c-946a-4e5102565244)

**Comment by digiofficerobin** [comment] 2024-10-08 14:46
Other uses on the Internet reporting this issue as well:
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/leave-modal-dialog-open-until-user-closes-it/idi-p/4265148#M2727
https://github.com/OfficeDev/office-js/issues/711
https://github.com/OfficeDev/office-js/issues/3761
https://github.com/OfficeDev/office-js/issues/3823

**Comment by Rick-Kirkham** [comment] 2024-10-08 18:16
@digiofficerobin Please go to [Office Add-ins platform overview](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins). In the Search bar, search on "five minutes". You'll get a lot of hits about 5 minute timeouts. See if any of them explain what you are seeing. 
<img width="299" alt="image" src="https://github.com/user-attachments/assets/f1cb308e-a350-4db3-80bf-d15ad2eaedf7">

**Comment by digiofficerobin** [comment] 2024-10-09 09:51
I have found this phrase:
> Once the user selects a button that kicks off the ExecuteFunction action, the add-in times out after 5 minutes if it hasn't completed by then.
source: https://learn.microsoft.com/en-us/javascript/api/manifest/action?view=common-js-preview

In the manifest we have declared this action:

```
<Action xsi:type="ExecuteFunction">
<FunctionName>openDialogOnNewEmail</FunctionName>
</Action>
```

The function 'openDialogOnNewEmail' looks like this:

```let dialog;
function openDialogOnNewEmail(event) {
  const url = window.location.origin + '#/emaildialog/compose';

  Office.context.ui.displayDialogAsync(
    url,
    { height: 80, width: 80,  displayInIframe: true },
    function (asyncResult) {
      dialog = asyncResult.value;
      if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
        LoggerService.writeMessage("Dialog opened successfully");
        dialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessageFromDialog);

        dialog.addEventHandler(Office.EventType.DialogEventReceived, function (event) {
          if (event.error === 12006) { // 12006 Dialog closed by user
            LoggerService.writeMessage('Dialog closed by user');
            Office.context.mailbox.item.close();
            dialog = null;
          }
        });
      } else {
        LoggerService.writeError("Error opening dialog:", asyncResult.error.message);
      }
    }
  );
}
```

Thus the action has a timeout of 5 minutes, but how do we suppose to show a dialog longer than 5 minutes?
I've found that we should call event.Complete() when the process is completed, but this will not allow the popup to render its content (the popup is shown, but keeps showing the busy loading circle animation).

> Add-in launch-event handlers are expected to be short-running, lightweight, and as noninvasive as possible. After activation, your add-in will time out within approximately 300 seconds, the maximum length of time allowed for running event-based add-ins. To signal that your add-in has completed processing a launch event, your associated event handler must call the [event.completed](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailboxevent#outlook-office-mailboxevent-completed-member(1)) method. (Note that code included after the event.completed statement isn't guaranteed to run.) Each time an event that your add-in handles is triggered, the add-in is reactivated and runs the associated event handler, and the timeout window is reset. The add-in ends after it times out, or the user closes the compose window or sends the item.
source: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch

By this behavior I guess that we should not use open a dialog when a function is called.

I found the following contradicting text at https://learn.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands:

> There are two types of add-in commands, based on the kind of action that the command triggers.
> 
> **Task pane commands:** The button or menu item opens the add-in's [task pane](https://learn.microsoft.com/en-us/office/dev/add-ins/design/task-pane-add-ins). You add this kind of add-in command with markup in the manifest. The "code behind" the command is provided by Office.
> **Function commands:** The button or menu item runs any arbitrary JavaScript. The code almost always calls APIs in the Office JavaScript Library, but it doesn't have to. This type of add-in typically displays no UI other than the button or menu item itself. Note the following about function commands:
> The function that is triggered can call the [displayDialogAsync](https://learn.microsoft.com/en-us/javascript/api/office/office.ui?view=common-js&preserve-view=true#office-office-ui-displaydialogasync-member(1)) method to show a dialog, **which is a good way to display an error, show progress, or prompt for input from the user**. If the add-in is configured to use a [shared runtime](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes#shared-runtime), the function can also call the [showAsTaskpane](https://learn.microsoft.com/en-us/javascript/api/office/office.addin#office-office-addin-showastaskpane-member(1)) method.
> The runtime in which the function command runs is a full [browser-based runtime](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes#browser-runtime). It can render HTML and call out to the Internet to send or get data.
> 

One article recommends the usage of the popup dialog, but the event/function implementation says it may only take 5 minutes (300 seconds) to complete the action. Thus requiring the user to fill the form within 5 minutes, which is way too short for our usage scenarios.

Are we forced to use the taskpane? We have some issues with the taskpane implementation, because its width is fixed (we need more width) and while composing an e-mail the our form have conflicts of interest.

**Comment by Rick-Kirkham** [comment] 2024-10-10 18:02
@digiofficerobin Thanks for the details. This confirms that the problem is a time-out policy. It looks like you won't be able to have a dialog that takes more than 5 minutes to fill out in an Outlook event-based add-in. You will need to use a task pane. If the task pane width is a problem, here are some things you can try:

1. Have the opening page of the task pane tell the user to widen the task pane. Have a button on the page that navigates to the "real" main page. 
2. Experiment with floating iFrames. See if you can design the task pane to have a floating iFrame that opens to the desired width. I haven't tried this, so I don't know if it would work. 
3. I don't know if this would work for your scenario, but you can combine an Outlook add-in with a custom Teams tab app in a single Microsoft 365 extension. A Teams tab app can be launched from the Outlook app bar on the left just as it can from the Teams app bar. Perhaps you could use the Teams tab to gather the user's input, send it to a backend database where the Outlook add-in can fetch it. There's a sample of a combined add-in and Teams tab app at [Combined Tab and Office Add-in](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-add-in-combined/nodejs). But I don't know well this architecture would fit with your event-based scenario. 

I will update the documentation to clarify that in the case of event-based Outlook apps, dialogs must be closed within 5 minutes. I'll close this issue for now, but you can still make comments and we will see them.

**Closed by Rick-Kirkham** 2024-10-10 18:02 UTC
Labels: Status: under investigation, Needs: attention :wave:, Area: add-ins
