### ISSUE TITLE
Register SSO Add-in Expose API instructions no longer working

### ISSUE THREAD

**Issue by westconference** [OfficeDev/office-js-docs-pr#3105] opened 2021-11-24 12:08 UTC
Step 5 of the instructions on registering an add-in for single-sign fails to work when trying to specify an add-in domain that is not registered as a custom domain.

> Select Expose an API under Manage. Select the Set link to generate the Application ID URI in the form "api://$App ID GUID$". Insert the $FQDN-WITHOUT-PROTOCOL$ (with a forward slash "/" appended to the end) between the double forward slashes and the GUID. The entire ID should have the form api://$FQDN-WITHOUT-PROTOCOL$/$App ID GUID$; for example api://localhost:6789/c6c1f32b-5e55-4997-881a-753cc1d563b7.

Our add-in service is used by O365 customers but they will not have the service URL added as a custom domain (they don't own it, we do). So attempting to register the add-in API causes the following error;
```
Failed to update Application ID URI application property. Error detail: Values of IdentifierUris property must use a verified domain of the organization or its subdomain: $addin_domain
```

Documentation indicates this should only be an issue for single-tenant applications but seeing this with multi-tenant applications also.
* https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#appid-uri-in-single-tenant-applications-will-require-use-of-default-scheme-or-verified-domains

Need updated instructions on how an add-in service can be registered for SSO with an Office 365 account that isn't able to add the external add-in service as a custom domain for that organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79094327-e4d3-da9a-e152-18408c0ffde2
* Version Independent ID: 120ecfb2-3d09-21bf-211e-e1e89050b52c
* Content: [Register an Office Add-in that uses SSO with the Azure AD v2.0 endpoint - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2)
* Content Source: [docs/develop/register-sso-add-in-aad-v2.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/register-sso-add-in-aad-v2.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2021-11-29 17:33
Thanks for reporting this issue @westconference.

@davidchesnut, could you please investigate?

**Comment by davidchesnut** [comment] 2022-01-19 18:45
Hi @westconference, 

I apologize for the delay responding on this issue. Taking a look there are several resources that may help here.

- You may need to follow steps for [adding a custom domain](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/add-custom-domain). 
- There's a similar Q&A thread around Microsoft Teams registration where the workaround is to use `https` instead of `api` on the application ID URI. https://docs.microsoft.com/en-us/answers/questions/271327/cannot-register-application-id-uri-apiinstanceserv.html

If the issue is still occurring, I recommend following up with the Microsoft identity platform team. They have help resources listed at https://docs.microsoft.com/en-us/azure/active-directory/develop/developer-support-help-options.

Hope this helps,
David

**Comment by davidchesnut** [comment] 2022-03-28 22:32
Will close this issue for now.

**Closed by davidchesnut** 2022-03-28 22:32 UTC
Labels: Area: authentication, Type: doc request, Needs: attention :wave:
