### ISSUE TITLE
Office.context.mailbox.item.addHandlerAsync api  not work after the iframe redirect or reload on MacOS chrome browser Office365 Outlook

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js-docs-pr#1445] opened 2019-11-21 10:53 UTC
[Enter feedback here]

For example:
Open "My Templates" add-on which every office365 outlook have this add-on. And open the developer tools in chrome. then select the "My templates" execute context. like the screen shot.
![image](https://user-images.githubusercontent.com/1878089/69331027-06133480-0c8f-11ea-9a04-41479015a114.png)
![image](https://user-images.githubusercontent.com/1878089/69331050-12978d00-0c8f-11ea-909c-ef7c74c26f39.png)
For the first time, when i execute Office.context.mailbox.item.addHandlerAsync, it  works when i change the meeting time in the appointment:
```
function handleAppointmentTimeChange() {
    console.log('111');
}

Office.context.mailbox.item.addHandlerAsync(Office.EventType.AppointmentTimeChanged, 
handleAppointmentTimeChange);
```

But when i redirect the page like execute the below code:
```
location.href = location.href
```

then re-execute the addHandlerAsync code like:
```
function handleAppointmentTimeChange() {
    console.log('111');
}

Office.context.mailbox.item.addHandlerAsync(Office.EventType.AppointmentTimeChanged, 
handleAppointmentTimeChange);
```
it doesn't work when i change the meeting time in the appointment.

Please track the issue, thanks~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5087f99-2e9c-3074-53dc-8507da1e74a4
* Version Independent ID: b9a838b9-1136-a3f2-14cb-d89d4b8672c1
* Content: [Office.context.mailbox.item - requirement set 1.7 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item)
* Content Source: [docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by hello-chenchen** [comment] 2019-11-21 10:56
This api works well on the outlook mac client

**Comment by slabereemsft** [comment] 2019-11-24 21:03
Appears to be a duplicate of https://github.com/OfficeDev/office-js/issues/865.  Given this is the doc repo and the other is in the product repo, we will look at the other one.

**Comment by slabereemsft** [comment] 2019-11-25 21:04
Closing as duplicate per comment above.

**Closed by slabereemsft** 2019-11-25 21:04 UTC
Labels: Needs: triage :mag:
