### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by mhelshou** [OfficeDev/office-js-docs-pr#465] opened 2018-10-14 08:16 UTC
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN my-office-add-in@0.1.0 No description
npm WARN my-office-add-in@0.1.0 No repository field.
npm WARN my-office-add-in@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

C:\my-onenote-addin\My Office Add-in\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\my-onenote-addin\My Office Add-in\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at Object.&lt;anonymous&gt; (C:\my-onenote-addin\My Office Add-in\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-office-add-in@0.1.0 start: `webpack-dev-server --mode development --https --key ./certs/server.key --cert ./certs/server.crt --cacert ./certs/ca.crt --port 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-office-add-in@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mhels\AppData\Roaming\npm-cache\_logs\2018-10-14T08_15_09_015Z-debug.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6ed3136-1d12-66c2-a8b1-1e7e43553aae
* Version Independent ID: 0e40308a-2d3d-a27b-04d5-1bdd7c09b501
* Content: [Build your first OneNote add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart)
* Content Source: [docs/quickstarts/onenote-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/onenote-quickstart.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment] 2018-10-15 17:39
@mhelshou I'm unable to reproduce the issue that you've described. Based on the errors you're seeing, I suspect that you may not be running the latest version of Yeoman and the Yeoman generator for Office Add-ins.  

Can you please try running the following command to install the latest versions of these tools globally, and then try creating/testing a new OneNote add-in as described in [Build your first OneNote add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart)? 

    npm install -g yo generator-office

Please let me know the result once you've had a chance to do this. Thanks!

**Comment by kbrandl** [comment] 2018-10-17 16:59
@mhelshou per my previous comment in this thread, I'm going to go ahead and close this issue now. Please feel free to re-open it if installing the latest versions of Yeoman and the Yeoman generator for Office Add-ins doesn't solve your problem. Also, please note that this article was updated yesterday to address some other minor issues.

**Closed by kbrandl** 2018-10-17 16:59 UTC
Labels: area: add-ins
