### ISSUE TITLE
Debugger setpoints won't work, error indicates symbols are not available

### ISSUE THREAD

**Issue by plmayfield** [OfficeDev/office-js-docs-pr#1141] opened 2019-06-28 21:40 UTC
When running this example, my debugger would give me a hollow red circle (in debug mode). It complained about no debug information. I tried VS 2017 and 2019 and nothing worked. After hours of research I worked out this solution. Change the tsconfig.json file to below. I added the "sourceMap" line. 

{
  "compilerOptions": {
    "skipLibCheck": true,
    "lib": [ "es5", "dom", "es2015.promise" ],
    "sourceMap": true
  }

**Comment by kbrandl** [comment] 2019-07-01 18:07
Closing this issue as a (partial) duplicate of #1142.

**Closed by kbrandl** 2019-07-01 18:07 UTC
