### ISSUE TITLE
Nuget Package no longer available from package manager

### ISSUE THREAD

**Issue by justingden** [OfficeDev/office-js-docs-pr#2859] opened 2021-08-05 18:33 UTC
The reference typescript Nuget Package no longer available from package manager. It would be good to get an updated way to acquire the typescript definitions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b888399c-fe96-0934-00ce-86db8fa8cf5b
* Version Independent ID: 2c5d24e8-5639-42b1-4d12-119f89591550
* Content: [Convert an Office Add-in project in Visual Studio to TypeScript - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript)
* Content Source: [docs/develop/convert-javascript-to-typescript.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/convert-javascript-to-typescript.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2021-08-05 18:42
Thanks for reporting this @justingden.

@Rick-Kirkham, could you please investigate?

**Comment by justingden** [comment] 2021-08-05 19:34
The solution I found is not easy for .NET framework projects as it looks
like TS has moved to npm. (.NET core now has native npm project support)

Here is an example:
https://stackoverflow.com/questions/32050645/how-to-use-jquery-with-typescript

I am just manually added package.json to the project and then using npm
from command line.

**Comment by Rick-Kirkham** [comment] 2021-08-10 16:56
Strange. My comment from a few days ago is gone. I wrote that I cannot reproduce. The jquery.TypeScript.DefinitelyTyped is available for installation in Visual Studio.

**Comment by justingden** [comment] 2021-08-10 18:01
Hi Rick,

I apologize for wasting your time. I think there was a package source
filter that somehow got applied. I see it now as well.

TypeScript has moved to npm packages for definition, so it might be worth a
note in the article, but there is no problem with what you have.

Thank you,

Justin

**Comment by Rick-Kirkham** [comment] 2021-08-10 19:58
Thanks. I'll close this for now.

**Closed by Rick-Kirkham** 2021-08-10 19:58 UTC
Labels: Type: doc bug, Needs: attention :wave:, Area: add-ins
