### ISSUE TITLE
The "document" property needs to go into the "config" section

### ISSUE THREAD

**Issue by matthias-glubrecht** [OfficeDev/office-js-docs-pr#2630] opened 2021-04-18 07:20 UTC
In order to enable debugging on the web, the "document" property needs to go into the "config" section, not into the "scripts" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab35128-1e97-c6ad-babc-f696f2e7b0fe
* Version Independent ID: cd1bacb1-14d7-a38d-321c-ebc2a526e03b
* Content: [Sideload Office Add-ins in Office on the web for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#sideload-an-office-add-in-in-office-on-the-web)
* Content Source: [docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-office-add-ins-for-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment] 2021-04-20 21:27
@matthias-glubrecht Thanks for raising this issue. I'm closing this as a duplicate of https://github.com/OfficeDev/office-js-docs-pr/issues/2623.

**Closed by ElizabethSamuel-MSFT** 2021-04-20 21:27 UTC
Labels: Area: add-ins, Resolution: duplicate, Type: doc bug
