### ISSUE TITLE
Request for missing error codes

### ISSUE THREAD

**Issue by DeanGross** [OfficeDev/office-js-docs-pr#2405] opened 2021-01-08 13:14 UTC
Please add all of the relevant error codes to this documentation. I am seeing 50058 and its not listed on this page
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 554083cc-a1e1-9c9d-da7d-7235b0fff31f
* Version Independent ID: 9923ac3f-0b95-e89f-f4f4-6da8e0a30c36
* Content: [Troubleshoot error messages for single sign-on (SSO) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins)
* Content Source: [docs/develop/troubleshoot-sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/troubleshoot-sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2021-01-08 19:09
Thanks for reporting this issue @DeanGross. We'll work to get the page updated. 

In the meantime, since this does not appear to be an error specific to add-ins, I found this article explaining the error code: https://code2care.org/q/microsoft-sign-in-error-code-50058-request-id-correlation-id-timestamp#:~:text=Error%20Code:%2050058:%20Message:%20Session%20information%20is%20not,is%20unauthenticated%20and%20has%20not%20yet%20signed%20in.

Is that enough information to unblock your development?

**Comment by Rick-Kirkham** [comment] 2021-01-13 00:41
@DeanGross Please clarify when you are seeing the error. Is it when you try to login to Office? When getAccessToken runs?

**Comment by DeanGross** [comment] 2021-01-13 13:28
@Rick-Kirkham  i am seeing this error in the Sign In Report in Azure AD

**Comment by Rick-Kirkham** [comment] 2021-01-13 18:13
I didn't know about that report, so I've never used it. What user event correlates with the error entry in the report? Is it when you try to login to Office? Or when getAccessToken runs? Or ... something else?

Also, I don't think we (Microsoft) wants to document errors that aren't returned by the Office JavaScript library itself in it's documentation for add-ins. What is happening in the add-in when this error is logged? Is there an error in the console?

**Comment by DeanGross** [comment] 2021-01-14 12:44
This is the [report](https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-reporting#:~:text=To%20review%20and%20understand%20Azure%20AD%20Multi-Factor%20Authentication,overview%20of%20sign-in%20activity%20reports%20in%20Azure%20AD.),  This occurred when an external user who had been invited to a Team attempted to respond to the invitation and login, the status showed as Interrupted.

**Comment by Rick-Kirkham** [comment] 2021-01-14 22:28
Thanks. This error doesn't have any connection with Office Add-ins. The article you found is only about errors reported when an Office Add-in calls an API function named `getAccesstoken`. That's not what was happening when you got the user got the error. 

I suggest that you have your network add-in and/or Azure help troubleshoot the cause of the error. 

I will close this.

**Closed by Rick-Kirkham** 2021-01-14 22:28 UTC
Labels: Area: authentication, Needs: attention :wave:, Type: doc request
