### ISSUE TITLE
These examples are not working or more information is needed.

### ISSUE THREAD

**Issue by DanilKorotenko** [OfficeDev/office-js-docs-pr#4059] opened 2023-06-15 13:10 UTC
I was unable to make these examples working. 
It may be possible that I missed some important thing in manifest and/or in overall addin code.

Please, visit my sample project:
https://github.com/DanilKorotenko/OutlookAddinSetInternetHeaders

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac0e08e9-b043-1a03-9505-2b3a9ca95e14
* Version Independent ID: e465cfb6-e349-1d24-30b2-2ea4bc56d976
* Content: [Get and set internet headers - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/internet-headers)
* Content Source: [docs/outlook/internet-headers.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/internet-headers.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by DanilKorotenko** [comment] 2023-06-15 13:14
Additional info:
This issue is absent in Outlook on the Web (https://outlook.office.com/)

**Comment by Rick-Kirkham** [comment] 2023-06-15 16:40
@DanilKorotenko This is a duplicate of [3393](https://github.com/OfficeDev/office-js/issues/3393), and it seems to be a bug in the platform, not an issue with the documentation. So, I will close the issue here. We don't want to be tracking the same issue in two places. If you want, you can add the link to your project to issue 3393.

**Closed by Rick-Kirkham** 2023-06-15 16:40 UTC
Labels: Needs: triage :mag:
